apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: wenrui-cao-pipeline-run-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: wenrui-cao-buildah-pipeline
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi